version: '3.8'

services:
  bot:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: telegram_bot
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app