version: '3.8'

services:
  bot:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: telegram_bot
    depends_on:
      - redis
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app

  redis:
    image: redis:7-alpine
    container_name: redis_server
    restart: unless-stopped
    ports:
      - "6379:6379"